### ISSUE TITLE
Feature Enhancements

### ISSUE THREAD

**Issue by jaymarvels** [PokemonTCG/pokemon-tcg-sdk-csharp#10]
@glinesbdev  @Spongie  

As the top 3 contributors I am just wondering what, if anything, we can do to enhance and continue to develop this sdk.

Any ideas?

**Comment by Spongie** [comment]
Creating async methods to enable async/await workflow would be nice.

**Comment by glinesbdev** [comment]
Great idea! Let me know if you have the capacity for that and I can jump in
if needed.

**Comment by glinesbdev** [comment]
Closing this stale issue.
