### ISSUE TITLE
Update NuGet Package

### ISSUE THREAD

**Issue by CriticalFlaw** [PokemonTCG/pokemon-tcg-sdk-csharp#14]
Hello. Can you upload an updated version of `PokemonTcgSdk` to NuGet, please? The live version still points to v1.0.0 and hasn't been updated since 2017. Thanks!

**Comment by jaymarvels** [comment]
@glinesbdev  Could we set up the repo to connect with MyGet so we can automatically push to nuget going forward?

**Comment by glinesbdev** [comment]
The nuget package is now updated to version 1.1.0 with the current master branch. 👍
