### ISSUE TITLE
No Energy Class found

### ISSUE THREAD

**Issue by Rosco666** [PokemonTCG/pokemon-tcg-sdk-csharp#16]
Hi, i installed via NuGet CommandLine and everything went fine except for one thing: in the documentation i saw the example:

var cards = Card.Get < Energy > ();
cards.Cards;

but there's no Energy.cs in the project and i can't use it.

thanks for the great job

Rosco

**Comment by jaymarvels** [comment]
@Rosco666  When you installed via command line which version did you specify? V 1.0.0 which is in the readme won't include Energy cards as these were only added in Nov 2020

Latest build does include Energy cards and you can see the unit tests pass for these too

**Comment by glinesbdev** [comment]
Sorry for the late response. As @jaymarvels outlines, you will need to use a version higher than 1.0.0. I've updated the README to reflect the latest version, 1.1.1.

**Comment by Rosco666** [comment]
thank you both.
Solved.
