### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by jaymarvels** [PokemonTCG/pokemon-tcg-sdk-csharp#17]
@glinesbdev 

Ideally we should have had a major version bump when we added support for .net core as this would be a breaking change from a dev perspective (you need .net core installed to develop on it)

Also, I think we should start tagging releases too to allow git to create release packages for non nuget use

**Comment by glinesbdev** [comment]
Yes, that is absolutely correct, that was my bad. Tagging isn't a bad idea, either 👍 Consider it done going forward.
