### ISSUE TITLE
V1 to V2 Migration

### ISSUE THREAD

**Issue by jaymarvels** [PokemonTCG/pokemon-tcg-sdk-csharp#18]
@glinesbdev 

We'll also need to look at migrating to v2 of the api, v1 currently is supported till Aug 2021.

If we could get access to a jira type system where we can spec out the changes needed we can get on with collaborating on this.

**Comment by glinesbdev** [comment]
Can you outline what we would need a Jira type system for? I've use Jira in the past but not their type system API. Can you outline the benefits?

**Comment by jaymarvels** [comment]
@glinesbdev More for a breakdown of tasks to implement v1 to v2, means for instance we could have 20 tasks to migrate to v2 and each change could be its own branch and PR so multiple developers could work on the migration rather than one and/or a duplication of work.

Just a way to manage the migration, unless you have other thoughts/process in place.

**Comment by glinesbdev** [comment]
@jaymarvels I created a board for the V1 -> V2 migration. Can you let me know if you can access it? https://csharp-pokemon-tcg-sdk.atlassian.net/jira/software/c/projects/CPAS/issues/

**Comment by jaymarvels** [comment]
@glinesbdev  Afraid I don't have access to it

**Comment by glinesbdev** [comment]
@jaymarvels ugh, unfortunately you have to explicitly invite people on the free plan which is the same situation I've run into with other products similar to Jira. Why not just use the GitHub issues tab in conjunction with tags?

**Comment by jaymarvels** [comment]
@glinesbdev  Whatever is easiest, I don't mind!

**Comment by jaymarvels** [comment]
@glinesbdev  instead of using the issues tab we could use the projects tab inside github instead?

**Comment by Serraniel** [comment]
I tried to give it a start and created a draft pull request (see #19 ). However this is far from being finished imo and only opened the draft PR as I probably will not have the time to continue a lot in the next weeks. More detail is written down inside the PR. 

Probably would be a nice idea to set up projects tab on Github if possible.
