### ISSUE TITLE
No property AncientTrait in Card or PokemonCard classes.

### ISSUE THREAD

**Issue by Fil0611** [PokemonTCG/pokemon-tcg-sdk-csharp#29]
This is the only problem I've encountered by now, the job you've done with the API is simply amazing.
I noticed that if a card has the key "ancientTrait", like Celebi (xyp-XY93), the value of the key cannot be accessed or read.

I'll attach the code I'm using, maybe it can help:
```c#
PokemonApiClient pokeClient = new PokemonApiClient("API-KEY");

// filter
var filter = PokemonFilterBuilder.CreatePokemonFilter()
    .AddId("xyp-XY93");

// get card
var card = await pokeClient.GetApiResourceAsync<PokemonCard>(filters: filter);
```

**Comment by jaymarvels** [comment]
This has been fixed in v2.2.1 which should be propagating through nuget shortly
