### ISSUE TITLE
Missing Tcg Pricing Properties

### ISSUE THREAD

**Issue by adwoold** [PokemonTCG/pokemon-tcg-sdk-csharp#34]
I noticed there is some missing data from the TcgPlayer.TcgPlayerPrices object on some cards. It appears that the base API is returning price data, but the C# SDK is not. My thought is additional properties in the Prices object needs to be added to properly deserialize the json.  
Below I'm including two examples of calls that work from the base API, but not the C# client. 
1) https://api.pokemontcg.io/v2/cards/neo3-20
2) https://api.pokemontcg.io/v2/cards/gym1-65

After inspecting the json returned from the above calls I can confirm that Prices data is being returned under the following TcgPlayerPrices properties: "1stEdition", "unlimited"
I will propose a change that has fixed the bug on a local fork of the client. Add the following two properties following this line: https://github.com/PokemonTCG/pokemon-tcg-sdk-csharp/blob/f7083beb890cc8b9c8a41dd391e73b0fb67043fc/PokemonTcgSdk.Standard/Infrastructure/HttpClients/Cards/Models/TcgPlayer.cs#L38

`[JsonProperty("1stEdition", NullValueHandling = NullValueHandling.Ignore)]
        public Prices The1stEdition { get; set; }`
`[JsonProperty("unlimited", NullValueHandling = NullValueHandling.Ignore)]
        public Prices Unlimited { get; set; }`

**Comment by jaymarvels** [comment]
Fixed in the latest release
