### ISSUE TITLE
List<PokemonCard> All() - not getting Text property of Trainers

### ISSUE THREAD

**Issue by rastoAtGit** [PokemonTCG/pokemon-tcg-sdk-csharp#8]
I have a question. Why when calling:

```
// Get all Pokemon cards (will take awhile)
List<PokemonCard> All(Dictionary<string, string> query)
```

we're getting PokemonCard? I mean, this way when Trainer cards are returned we're missing Text property of TrainerCard. Would be nice to have a Class here that would contain all the properties of pokemon card returned by TCG API. But I guess that would mean a bigger redesign of C# SDK. And it's not that big issue, cause one can always get this extra Text property by calling Find<Trainer> when dealing with TrainerCard...

**Comment by glinesbdev** [comment]
So do you mean to say create a total generic class that can handle Trainer and Pokemon cards simultaneously?

**Comment by rastoAtGit** [comment]
right now I see:
```
public class PokemonCard : PokemonTcgSdk.Models.BaseCard
public class TrainerCard : PokemonTcgSdk.Models.BaseCard
```
but I guess there's a reason for doing it this way. I mean I would have one generic class that would contain all the possible properties coming from https://api.pokemontcg.io. For me that would be enough and I would just use SuperType to see if it is Pokemon or Trainer. But I guess there was an idea behind this two classes (PokemonCard & TrainerCard).

Reason why I asked is that I was playing a bit with this C# SDK and I wanted to use this ALL method to get all the cards and their possible properties and import all that info into my mongodb as a test project while playing with mongodb. So I was missing that Text property of TrainerCard. Really not that big issue :)

**Comment by glinesbdev** [comment]
Closed due to long inactivity.

**Comment by jaymarvels** [comment]
I think the base class is the correct oop way of doing this and not some massive generic class

**Comment by glinesbdev** [comment]
Issue was closed due to no development work is needed. If there are any further questions, please open another issue.
